sudo: false
language: csharp
solution: src/Susanoo.sln
install:
  - .paket\paket.bootstrapper.exe
  - .paket\paket.exe restore

script:    # the following commands are just examples, use whatever your build process requires
  - xbuild /p:Configuration=Mono src/Susanoo.sln
