version: 1.2.4.{build}
skip_tags: true
os: Visual Studio 2015
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- cmd: >-
    set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

    .paket\paket.bootstrapper.exe

    .paket\paket.exe restore
build:
  verbosity: minimal
after_build:
- cmd: >-
    .paket\paket.exe pack output nupkgs

artifacts:
- path: nupkgs\*.nupkg
  name: nupkgs